#!/usr/bin/env python3

from microdude.editor import Editor
import microdude.utils
import signal
import setproctitle


def quit(signum, frame):
    editor.quit()


signal.signal(signal.SIGINT, quit)

setproctitle.setproctitle(microdude.utils.APP_NAME)
editor = Editor()
editor.main()
